#action.yml

name: 'GitHub Action for M365 License Cleanup Report'
description: 'This action will create a report  M365 licenses from users that has not used in last 30 days.'
inputs:
  tenant_id: #input id
    description: 'Entra Tenant ID'
    required: true
    default: ''
  email_recipient: #input id
    description: 'Email of the Recipient of the report'
runs: 
  using: "Composite"
  steps:
  - id: cd
    run: |
      cd .\${{ github.action_path }}
  - id: license-report
    run: |
      .\${{ github.action_path }}\M365-License-Checker.ps1 -tenant_id ${{ inputs.tenant_id }} >> $GITHUB_OUTPUT
    shell: PowerShell
