#action.yml

name: 'GitHub Action for M365 License Cleanup Report'
description: 'This action will create a report  M365 licenses from users that has not used in last 30 days.'
inputs:
  license_id: #input id
    description: 'Entra License ID'
    required: true
    default: ''
  email_recipient: #input id
    description: 'Email of the Recipient of the report'
runs: 
  using: "Composite"
  steps:
  - id:  license-report
    run: |
      cd ${{ github.action_path }} 
      .\M365-License-Checker.ps1
    shell: PowerShell

